# Generated by Django 5.2.8 on 2026-06-01 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('credits', models.PositiveSmallIntegerField(default=3)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(default=100)),
                ('venue_type', models.CharField(choices=[('lecture', 'Lecture Hall'), ('lab', 'Laboratory'), ('auditorium', 'Auditorium')], default='lecture', max_length=20)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('I', 'Level I'), ('II', 'Level II'), ('III', 'Level III')], max_length=5)),
                ('stream', models.CharField(choices=[('physical', 'Physical Science'), ('bio', 'Bio Science'), ('both', 'Both')], max_length=10)),
                ('subgroup', models.CharField(blank=True, max_length=10)),
                ('year', models.CharField(default='2024', max_length=4)),
            ],
            options={
                'ordering': ['level', 'stream', 'subgroup'],
                'unique_together': {('level', 'stream', 'subgroup', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['day', 'start_time'],
                'unique_together': {('day', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(default='S2-2026', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='api.course')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='api.lecturer')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='api.studentgroup')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='api.timeslot')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='api.venue')),
            ],
            options={
                'ordering': ['timeslot__day', 'timeslot__start_time'],
            },
        ),
    ]
