# Generated by Django 5.2.8 on 2026-07-06 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_lecturernotification_lecturerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='student_avatars/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('audience', models.CharField(choices=[('FACULTY', 'Faculty-wide'), ('BATCH', 'Batch-wide'), ('GROUP', 'Student group')], default='FACULTY', max_length=20)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('student_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='api.studentgroup')),
            ],
        ),
        migrations.CreateModel(
            name='StudentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('RESCHEDULE', 'Class reschedule'), ('CANCEL', 'Class cancellation'), ('ROOM_CHANGE', 'Room change'), ('GENERAL', 'General notice')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_notifications', to='api.scheduleslot')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notifications', to='api.studentgroup')),
            ],
        ),
    ]
