# Generated by Django 4.2.7 on 2026-07-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_avatar_userprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=20)),
                ('publisher', models.CharField(max_length=100)),
                ('initials', models.CharField(blank=True, max_length=4)),
                ('notes', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', '-id'],
            },
        ),
    ]
