# Generated by Django 6.0.6 on 2026-07-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_lecturer_lecturer_id_lecturer_must_change_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='student_groups', to='api.course'),
        ),
    ]
