# Generated by Django 4.2.7 on 2026-07-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_studentgroup_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='subgroup',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
