# Generated by Django 4.2.7 on 2026-07-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_studentgroup_subgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=4),
        ),
    ]
