# Generated by Django 6.0.6 on 2026-08-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_course_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleslot',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
